name: Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |-
              linux/arm64
          file: ./Dockerfile
          push: true
          pull: true
          tags: danigrb/jam2021:keycloak-custom
          cache-from: type=registry,ref=danigrb/jam2021:buildcache
          cache-to: type=registry,ref=danigrb/jam2021:buildcache,mode=max
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
